name: Lint

permissions:
  checks: write
  contents: write

on:
    push:
      branches: ["main"]
    pull_request:
      # The branches below must be a subset of the branches above
      branches: ["main"]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint Action
        uses: rkuykendall/lint-action@master
